import 'package:flutter/material.dart';

/* Group login button
    Autogenerated by FlutLab FTF Generator
  */
class LoginBtn extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedHomePageContactListWidget1'),
      child: Container(
        width: 120.0,
        height: 60.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: null,
                right: null,
                bottom: 0.0,
                width: 120.0,
                height: 60.0,
                child: Container(
                  width: 120.0,
                  height: 60.0,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10.0),
                    border: Border.all(
                      width: 1.0,
                      color: Color.fromARGB(255, 255, 255, 255),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33.846160888671875,
                top: null,
                right: null,
                bottom: 14.0,
                width: 57.30769348144531,
                height: 27.0,
                child: Align(
                  alignment: Alignment.center,
                  child: Text(
                    '''Login''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      height: 1.171875,
                      fontSize: 18.0,
                      fontFamily: 'Nunito',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 255, 255, 255),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
              )
            ]),
      ),
    );
  }
}
