import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedintrowidget/generated/GeneratedHealthKatWidget4.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedintrowidget/generated/GeneratedToolsStatusBarDarkWidget8.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedintrowidget/generated/GeneratedLoginBtnWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedintrowidget/generated/GeneratedFinalremovebg1Widget.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedintrowidget/generated/GeneratedLoginBtnWidget1.dart';

/* Frame Intro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(102, 16, 245, 39),
                ),
              ),
              Positioned(
                left: 83.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 295.0,
                child: GeneratedFinalremovebg1Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 56.0,
                child: GeneratedHealthKatWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.02955665111541748;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsStatusBarDarkWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 66.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 57.78947448730469,
                child: GeneratedLoginBtnWidget(),
              ),
              Positioned(
                left: 67.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 57.78947448730469,
                child: GeneratedLoginBtnWidget1(),
              )
            ]),
      ),
    ));
  }
}
