import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedNEWWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedCalendarWidget3.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedEDITWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedToolsStatusBarDarkWidget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedTabBarWidget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedTopBarSearchWidget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedCalendarWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendarwidget1/generated/GeneratedToolsNavBarWidget1.dart';

/* Frame Calendar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedDiscoverWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 708.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 87.0,
                  child: GeneratedTabBarWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 44.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 110.76923370361328,
                  child: GeneratedTopBarSearchWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.2833333333333333;

                    final double height =
                        constraints.maxHeight * 0.05874992370605469;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.20555555555555555,
                          y: constraints.maxHeight * 0.77125,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedNEWWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: -1967.0,
                  top: -36.15789794921875,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 276.0,
                  child: GeneratedCalendarWidget2(),
                ),
                Positioned(
                  left: 211.0,
                  top: 616.0,
                  right: null,
                  bottom: null,
                  width: 102.0,
                  height: 48.0,
                  child: GeneratedEDITWidget(),
                ),
                Positioned(
                  left: 41.0,
                  top: 228.0,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 276.0,
                  child: GeneratedCalendarWidget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth;

                    final double height =
                        constraints.maxHeight * 0.02955665111541748;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: 0,
                          y: 0,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedToolsStatusBarDarkWidget1(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth;

                    final double height =
                        constraints.maxHeight * 0.05911331176757813;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: 0,
                          y: constraints.maxHeight * 0.9396551513671875,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedToolsNavBarWidget1(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
