import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedNewHereRegisterWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedHealthKatWidget6.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedToolsStatusBarDarkWidget10.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedLoginbuttonWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedloginpagewidget/generated/GeneratedFinalremovebg1Widget1.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(102, 16, 245, 39),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: GeneratedFinalremovebg1Widget1(),
              ),
              Positioned(
                left: 167.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 84.0,
                child: GeneratedHealthKatWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.02955665111541748;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsStatusBarDarkWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 19.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 72.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 25.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 26.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 51.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 51.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 243.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 43.0,
                child: GeneratedNewHereRegisterWidget(),
              ),
              Positioned(
                left: 211.0,
                top: null,
                right: null,
                bottom: 316.0,
                width: 120.0,
                height: 60.0,
                child: GeneratedLoginbuttonWidget(),
              )
            ]),
      ),
    ));
  }
}
