import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedToolsNavBarWidget14.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedPrivacyWidget4.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedEllipse2Widget8.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedMoreActionsWidget2.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedToolsStatusBarDarkWidget22.dart';
import 'package:flutterapp/healthkatapp/Screens/Profile/generated/GeneratedProfileBarWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 340.0,
        height: 729.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 184.0,
                child: GeneratedPrivacyWidget4(),
              ),
              Positioned(
                left: -1.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 191.0,
                child: GeneratedMoreActionsWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 430.0381774902344,
                child: GeneratedProfileBarWidget1(),
              ),
              Positioned(
                left: 140.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 105.0,
                child: GeneratedEllipse2Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.029556651174286266;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsStatusBarDarkWidget22(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.059113260486325446;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9458128375771605,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsNavBarWidget14(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
