import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Components/Login/PasswordTextField.dart';
import 'package:flutterapp/healthkatapp/Components/Login/EmailTextField.dart';
import 'package:flutterapp/healthkatapp/Components/Login/LoginBtn.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(102, 16, 245, 39),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 149.0,
                child: TransformHelper.rotate(
                    a: 1.00,
                    b: 0.00,
                    c: -0.00,
                    d: 1.00,
                    child: Container(
                      width: 138.0,
                      height: 149.0,
                      child: ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Image.asset(
                          "assets/images/e2d8d45024b98f2c2e70b2467761b0cdd8a07c7a.png",
                          color: null,
                          fit: BoxFit.cover,
                          width: 138.0,
                          height: 149.0,
                          colorBlendMode: BlendMode.dstATop,
                        ),
                      ),
                    )),
              ),
              Positioned(
                left: 167.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 84.0,
                child: Text(
                  '''Health Kat''',
                  overflow: TextOverflow.visible,
                  textAlign: TextAlign.left,
                  style: TextStyle(
                    height: 1.171875,
                    fontSize: 50.0,
                    fontFamily: 'Roboto',
                    fontWeight: FontWeight.w400,
                    color: Color.fromARGB(255, 0, 0, 0),

                    /* letterSpacing: 0.0, */
                  ),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 72.0,
                child: Text(
                  '''Login''',
                  overflow: TextOverflow.visible,
                  textAlign: TextAlign.left,
                  style: TextStyle(
                    height: 1.171875,
                    fontSize: 36.0,
                    fontFamily: 'Nunito',
                    fontWeight: FontWeight.w700,
                    color: Color.fromARGB(255, 255, 255, 255),

                    /* letterSpacing: 0.0, */
                  ),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 25.0,
                child: Text(
                  '''Email''',
                  overflow: TextOverflow.visible,
                  textAlign: TextAlign.left,
                  style: TextStyle(
                    height: 1.171875,
                    fontSize: 16.0,
                    fontFamily: 'Nunito',
                    fontWeight: FontWeight.w400,
                    color: Color.fromARGB(255, 255, 255, 255),

                    /* letterSpacing: 0.0, */
                  ),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 26.0,
                child: Text(
                  '''Password''',
                  overflow: TextOverflow.visible,
                  textAlign: TextAlign.left,
                  style: TextStyle(
                    height: 1.171875,
                    fontSize: 16.0,
                    fontFamily: 'Nunito',
                    fontWeight: FontWeight.w400,
                    color: Color.fromARGB(255, 255, 255, 255),

                    /* letterSpacing: 0.0, */
                  ),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 51.0,
                child: EmailTextField(),
              ),
              Positioned(
                left: 19.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 51.0,
                child: PasswordTextField(),
              ),
              Positioned(
                left: 243.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 43.0,
                child: GestureDetector(
                  onTap: () => Navigator.pushNamed(context, '/GeneratedRegisterPageWidget'),
                  child: RichText(
                      overflow: TextOverflow.visible,
                      textAlign: TextAlign.left,
                      text: const TextSpan(
                        style: TextStyle(
                          height: 1.171875,
                          fontSize: 16.0,
                          fontFamily: 'Nunito',
                          fontWeight: FontWeight.w700,
                          color: Color.fromARGB(255, 255, 255, 255),

                          /* letterSpacing: 0.0, */
                        ),
                        children: [
                          TextSpan(
                            text: '''New Here?''',
                            style: TextStyle(
                              fontSize: 16.0,
                              fontFamily: 'Nunito',
                              fontWeight: FontWeight.w400,

                              /* letterSpacing: null, */
                            ),
                          ),
                          TextSpan(
                            text: ''' 
Register''',
                            style: TextStyle(
                              fontSize: 16.0,

                              /* letterSpacing: null, */
                            ),
                          )
                        ],
                      )),
                ),
              ),
              Positioned(
                left: 211.0,
                top: null,
                right: null,
                bottom: 316.0,
                width: 120.0,
                height: 60.0,
                child: LoginBtn(),
              )
            ]),
      ),
    ));
  }
}
