import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedCalendarWidget12.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedTabBarWidget7.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedInputTimePickerWidget3.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedToolsStatusBarDarkWidget20.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedTextFieldWidget3.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedButtonsWidget1.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedTopBarSearchWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/generatedcalendartimepickerwidget1/generated/GeneratedToolsNavBarWidget12.dart';

/* Frame Calendar - Time Picker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendarTimePickerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 340.0,
        height: 729.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 87.0,
                child: GeneratedTabBarWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.76923370361328,
                child: GeneratedTopBarSearchWidget7(),
              ),
              Positioned(
                left: -1967.0,
                top: -36.15789794921875,
                right: null,
                bottom: null,
                width: 280.0,
                height: 276.0,
                child: GeneratedCalendarWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.029556651174286266;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsStatusBarDarkWidget20(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.059113260486325446;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9396551522044324,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsNavBarWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 28.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 56.0,
                child: GeneratedTextFieldWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 547.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 36.0,
                child: GeneratedButtonsWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 250.0,
                child: GeneratedInputTimePickerWidget3(),
              )
            ]),
      ),
    ));
  }
}
