import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/Generated1644Widget.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedTopBarWidget4.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedGgmoreverticaloWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedToolsNavBarWidget5.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedSendMessageWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedElevationWidget6.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedToolsStatusBarDarkWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedMessagesGroupWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Chat/generated/GeneratedREQUESTNEWAPPOINTMENTWidget.dart';

/* Frame Chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedHomePageContactListWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 173.0,
                  top: 596.0,
                  right: null,
                  bottom: null,
                  width: 35.0,
                  height: 19.0,
                  child: Generated1644Widget(),
                ),
                Positioned(
                  left: 16.0,
                  top: 641.0,
                  right: null,
                  bottom: null,
                  width: 208.0,
                  height: 66.0,
                  child: GeneratedMessagesGroupWidget(),
                ),
                Positioned(
                  left: -7.0,
                  top: 707.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 87.0,
                  child: GeneratedSendMessageWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: -1.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 96.0,
                  child: GeneratedTopBarWidget4(),
                ),
                Positioned(
                  left: 16.0,
                  top: 715.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 36.0,
                  child: GeneratedGgmoreverticaloWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: null,
                  right: 0.0,
                  bottom: null,
                  width: null,
                  height: 51.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: -285.50,
                      z: 0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.9444444444444444;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.03333333333333333,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                child: GeneratedElevationWidget6(),
                              ))
                        ]);
                      })),
                ),
                Positioned(
                  left: 78.0,
                  top: 106.0,
                  right: null,
                  bottom: null,
                  width: 229.0,
                  height: 15.0,
                  child: GeneratedREQUESTNEWAPPOINTMENTWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth;

                    final double height =
                        constraints.maxHeight * 0.02955665111541748;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: 0,
                          y: 0,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedToolsStatusBarDarkWidget5(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth;

                    final double height =
                        constraints.maxHeight * 0.05911331176757813;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: 0,
                          y: constraints.maxHeight * 0.9470442962646485,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedToolsNavBarWidget5(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
