import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedHealthKatWidget5.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedToolsStatusBarDarkWidget9.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedFullNameWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedRegisterbtnWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedFinalremovebg2Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedRegisterWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedAlreadyaMemberLoginWidget.dart';
import 'package:flutterapp/healthkatapp/Screens/Register/generated/GeneratedRectangle2Widget.dart';

/* Frame Register Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(102, 16, 245, 39),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.02955665111541748;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsStatusBarDarkWidget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3680000305175781;

                  final double height =
                      constraints.maxHeight * 0.18349752426147461;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08266666730244955,
                        y: constraints.maxHeight * 0.02955665111541748,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFinalremovebg2Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4908888498942057;

                  final double height =
                      constraints.maxHeight * 0.1034852123260498;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4506666819254557,
                        y: constraints.maxHeight * 0.0825123119354248,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedHealthKatWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5738889058430989;

                  final double height =
                      constraints.maxHeight * 0.08876228332519531;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666663699679905,
                        y: constraints.maxHeight * 0.2660098648071289,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRegisterWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2672222137451172;

                  final double height =
                      constraints.maxHeight * 0.030880546569824217;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08266666730244955,
                        y: constraints.maxHeight * 0.4618226623535156,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEmailWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2588888804117839;

                  final double height =
                      constraints.maxHeight * 0.027130546569824218;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08266666730244955,
                        y: constraints.maxHeight * 0.3682265853881836,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFullNameWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2672222137451172;

                  final double height =
                      constraints.maxHeight * 0.030880546569824217;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08266666730244955,
                        y: constraints.maxHeight * 0.5554187393188477,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPasswordWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8267777336968316;

                  final double height =
                      constraints.maxHeight * 0.06282634735107422;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666663699679905,
                        y: constraints.maxHeight * 0.4433497619628906,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle1Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8267777336968316;

                  final double height =
                      constraints.maxHeight * 0.06282630920410157;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666663699679905,
                        y: constraints.maxHeight * 0.34975372314453124,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle4Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8267777336968316;

                  final double height =
                      constraints.maxHeight * 0.06282638549804688;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666663699679905,
                        y: constraints.maxHeight * 0.53694580078125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle2Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.37333331637912326;

                  final double height =
                      constraints.maxHeight * 0.07389163970947266;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5146666632758247,
                        y: constraints.maxHeight * 0.630541877746582,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRegisterbtnWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.354888916015625;

                  final double height =
                      constraints.maxHeight * 0.049298095703125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.591999986436632,
                        y: constraints.maxHeight * 0.7339900970458985,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAlreadyaMemberLoginWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
