import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedEventWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedTopBarSearchWidget5.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedCalendarWidget8.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedToolsNavBarWidget10.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedDoNotRecordWidget3.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedTabBarWidget5.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedToolsStatusBarDarkWidget18.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedEventWidget5.dart';
import 'package:flutterapp/healthkatapp/Screens/CalendarExpanded/generated/GeneratedEventWidget3.dart';

/* Frame Calendar - Expanded
    Autogenerated by FlutLab FTF Generator
  */
class CalendarExpanded extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 340.0,
        height: 729.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 709.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.0,
                child: GeneratedTabBarWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.76923370361328,
                child: GeneratedTopBarSearchWidget5(),
              ),
              Positioned(
                left: 40.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 276.0,
                child: GeneratedCalendarWidget8(),
              ),
              Positioned(
                left: 42.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 51.0,
                child: GeneratedEventWidget3(),
              ),
              Positioned(
                left: 42.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 51.0,
                child: GeneratedEventWidget4(),
              ),
              Positioned(
                left: 42.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 56.0,
                child: GeneratedEventWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.029556651174286266;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsStatusBarDarkWidget18(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.059113260486325446;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9396551522044324,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedToolsNavBarWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 51.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 48.0,
                child: GeneratedDoNotRecordWidget3(),
              )
            ]),
      ),
    ));
  }
}
