import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Components/Intro/LoginBtn.dart';
import 'package:flutterapp/healthkatapp/Components/Intro/RegisterBtn.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Intro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 360.0,
            height: 800.0,
            child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(102, 16, 245, 39),
                  ),
                ),
                Positioned(
                  left: 83.0,
                  top: 42.0,
                  right: null,
                  bottom: null,
                  width: 266.0,
                  height: 295.0,
                  child: TransformHelper.rotate(
                      a: 1.00,
                      b: 0.00,
                      c: -0.00,
                      d: 1.00,
                      child: Container(
                        width: 266.0,
                        height: 295.0,
                        child: ClipRRect(
                          borderRadius: BorderRadius.zero,
                          child: Image.asset(
                            "assets/images/e2d8d45024b98f2c2e70b2467761b0cdd8a07c7a.png",
                            color: null,
                            fit: BoxFit.cover,
                            width: 266.0,
                            height: 295.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      )),
                ),
                Positioned(
                  left: 79.0,
                  top: 337.0,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 56.0,
                  child: Text(
                    '''Health Kat''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.171875,
                      fontSize: 50.0,
                      fontFamily: 'WinterSong',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 0, 0, 0),
                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
                Positioned(
                  left: 66.0,
                  top: 570.0,
                  right: null,
                  bottom: null,
                  width: 240.0,
                  height: 57.78947448730469,
                  child: LoginBtn(),
                ),
                Positioned(
                  left: 67.0,
                  top: 663.0,
                  right: null,
                  bottom: null,
                  width: 240.0,
                  height: 57.78947448730469,
                  child: RegisterBtn(),
                )
              ]),
          ),
    ));
  }
}
