import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/generatednewappointmentwidget/generated/GeneratedElevationWidget5.dart';
import 'package:flutterapp/healthkatapp/Screens/generatednewappointmentwidget/generated/GeneratedSENDITWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/generatednewappointmentwidget/generated/GeneratedCalendarWidget5.dart';

/* Frame New Appointment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewAppointmentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 303.0,
          height: 416.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: null,
                  right: 0.0,
                  bottom: null,
                  width: null,
                  height: 36.0,
                  child: TransformHelper.translate(
                      x: 0.00,
                      y: 151.00,
                      z: 0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.45544554455445546;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.2607260726072607,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                child: GeneratedElevationWidget5(),
                              ))
                        ]);
                      })),
                ),
                Positioned(
                  left: 116.0,
                  top: 354.0,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 15.0,
                  child: GeneratedSENDITWidget(),
                ),
                Positioned(
                  left: 11.0,
                  top: 21.0,
                  right: null,
                  bottom: null,
                  width: 280.0,
                  height: 285.0,
                  child: GeneratedCalendarWidget5(),
                )
              ]),
        ),
      ),
    ));
  }
}
