import 'package:flutter/material.dart';
import 'package:flutterapp/healthkatapp/Screens/Discover/generated/GeneratedTabBarWidget3.dart';
import 'package:flutterapp/healthkatapp/Screens/Discover/generated/GeneratedPeopleWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/healthkatapp/Screens/Discover/generated/GeneratedTopBarWidget3.dart';
import 'package:flutterapp/healthkatapp/Screens/Discover/generated/GeneratedToolsNavBarWidget3.dart';
import 'package:flutterapp/healthkatapp/Screens/Discover/generated/GeneratedSearchWidget.dart';

/* Frame Discover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscoverWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedCalendarWidget1'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: -1.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 88.0,
                  child: GeneratedTopBarWidget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 87.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedSearchWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 142.0,
                  right: null,
                  bottom: null,
                  width: 359.0,
                  height: 636.0,
                  child: GeneratedPeopleWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 701.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 95.0,
                  child: GeneratedTabBarWidget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width = constraints.maxWidth;

                    final double height =
                        constraints.maxHeight * 0.05911331176757813;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.002666666607062022,
                          y: constraints.maxHeight * 0.9408866882324218,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedToolsNavBarWidget3(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
